// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAEW7xoSW-5fXrZP4mK0jA7sZIPKaJysM',
    appId: '1:56561787294:web:c3df817fd06a711d6bb68f',
    messagingSenderId: '56561787294',
    projectId: 'desafio-chat-flutter',
    authDomain: 'desafio-chat-flutter.firebaseapp.com',
    databaseURL: 'https://desafio-chat-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-chat-flutter.firebasestorage.app',
    measurementId: 'G-D7JCCNBYLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsavfhfAJJEhFo9_5z4cM6y22sjc0kKoo',
    appId: '1:56561787294:android:9de2049e845db50d6bb68f',
    messagingSenderId: '56561787294',
    projectId: 'desafio-chat-flutter',
    databaseURL: 'https://desafio-chat-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-chat-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgzSHQYjhTLY7GpY-eFPkRw6OeoUJyYJY',
    appId: '1:56561787294:ios:4025d4c63633c2b76bb68f',
    messagingSenderId: '56561787294',
    projectId: 'desafio-chat-flutter',
    databaseURL: 'https://desafio-chat-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-chat-flutter.firebasestorage.app',
    iosBundleId: 'com.example.desafioChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgzSHQYjhTLY7GpY-eFPkRw6OeoUJyYJY',
    appId: '1:56561787294:ios:4025d4c63633c2b76bb68f',
    messagingSenderId: '56561787294',
    projectId: 'desafio-chat-flutter',
    databaseURL: 'https://desafio-chat-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-chat-flutter.firebasestorage.app',
    iosBundleId: 'com.example.desafioChatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAEW7xoSW-5fXrZP4mK0jA7sZIPKaJysM',
    appId: '1:56561787294:web:44857ffe08a2bed56bb68f',
    messagingSenderId: '56561787294',
    projectId: 'desafio-chat-flutter',
    authDomain: 'desafio-chat-flutter.firebaseapp.com',
    databaseURL: 'https://desafio-chat-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-chat-flutter.firebasestorage.app',
    measurementId: 'G-XG187QPYWH',
  );

}